spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    com.straujupite: DEBUG
  config: classpath:logback.xml

server:
  error:
    include-message: always
  port: ${API_PORT}

path:
  web-client-url: "${OUTGOING_REQUEST_URL}"
